# Generated by Django 3.1.1 on 2020-09-05 15:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0002_auto_20200905_1850'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tag',
            old_name='stug',
            new_name='slug',
        ),
    ]
